name: on-release
on:
  release:
    types: [released]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          scope: "@ngx-dropzone"
          always-auth: true
          token: ${{ secrets.NPM_TOKEN }}
      - uses: oven-sh/setup-bun@v1
      - run: bun install

      - run: bun run build:cdk
      - run: bun run build:material

      - name: Publish CDK to npm
        working-directory: dist/cdk
        run: npm version ${{ github.ref_name }} && npm publish

      - name: Publish Material to npm
        working-directory: dist/material
        run: npm version ${{ github.ref_name }} && npm publish
